Now we need this module code to be available for a DaVinci build
git-svn-id: http://oss.mars.asu.edu/svn/davinci/iomedley/trunk@938 dedd6328-c50f-0410-8be5-b54a49638459

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -887,7 +887,7 @@ else
   fi
 fi
 
-for ac_prog in mawk gawk nawk awk
+for ac_prog in gawk mawk nawk awk
 do
 # Extract the first word of "$ac_prog", so it can be a program name with args.
 set dummy $ac_prog; ac_word=$2
@@ -2839,7 +2839,7 @@ fi
 		MAGICK_LDFLAGS=`$MAGICK_CONFIG --ldflags`
 	fi
 
-		if test "$MAGICK_VERSION" = "4.2.9"
+		if test "$MAGICK_VERSION" = "5.4.2"
 	then
 		save_CPPFLAGS="$CPPFLAGS"
 		save_CFLAGS="$CFLAGS"
@@ -2850,10 +2850,10 @@ fi
 		*-linux-gnu)  CFLAGS="$CFLAGS -I/usr/X11R6/include/X11"
 		esac
 
-		CPPFLAGS="$CPPFLAGS $MAGICK_CPPFLAGS"
-		CFLAGS="$CFLAGS $MAGICK_CFLAGS"
-		LIBS="$LIBS $MAGICK_LIBS"
-		LDFLAGS="$LDFLAGS $MAGICK_LDFLAGS"
+		CPPFLAGS="$MAGICK_CPPFLAGS $CPPFLAGS"
+		CFLAGS="$MAGICK_CFLAGS $CFLAGS"
+		LIBS="$MAGICK_LIBS $LIBS"
+		LDFLAGS="$MAGICK_LDFLAGS $LDFLAGS"
 
 												
 				echo $ac_n "checking for GetMagickInfo in -lMagick""... $ac_c" 1>&6
@@ -2910,7 +2910,7 @@ else
 fi
 
 	else
-		echo "configure: warning: ImageMagick version 4.2.9 required for compiling with ImageMagick" 1>&2
+		echo "configure: warning: ImageMagick version 5.4.2 required for compiling with ImageMagick" 1>&2
 	fi
 fi
 
